# Generated by Django 6.0.6 on 2026-06-27 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magang', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mahasiswa',
            new_name='Magang',
        ),
    ]
