# Generated by Django 6.0.6 on 2026-06-28 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magang', '0002_rename_mahasiswa_magang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bagian', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GuruPembimbing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nidn', models.CharField(max_length=50, unique=True)),
                ('mata_pelajaran', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JurnalHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('deskripsi_aktivitas', models.TextField()),
                ('lampiran_foto', models.CharField(blank=True, max_length=255, null=True)),
                ('status_validasi', models.CharField(max_length=50)),
                ('catatan_validasi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lamaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_lamaran', models.DateField()),
                ('status_lamaran', models.CharField(max_length=50)),
                ('catatan_admin', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_laporan', models.CharField(max_length=255)),
                ('file_laporan', models.CharField(max_length=255)),
                ('tanggal_upload', models.DateField(auto_now_add=True)),
                ('revisi_ke', models.IntegerField(default=0)),
                ('catatan_pembimbing', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lowongan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_posisi', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('kriteria', models.TextField()),
                ('kuota_tersedia', models.IntegerField()),
                ('tanggal_dibuat', models.DateField(auto_now_add=True)),
                ('batas_lamaran', models.DateField()),
                ('status_lowongan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MagangPenempatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('status_magang', models.CharField(max_length=50)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('id_guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penempatan_guru', to='magang.gurupembimbing')),
                ('id_lowongan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penempatan_lowongan', to='magang.lowongan')),
            ],
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_industri', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nilai_laporan', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nilai_ujian_akhir', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nilai_akhir', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rekomendasi_perusahaan', models.TextField(blank=True, null=True)),
                ('tanggal_input_industri', models.DateField()),
                ('tanggal_input_guru', models.DateField()),
                ('id_magang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_magang', to='magang.magangpenempatan')),
            ],
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('pesan', models.TextField()),
                ('jenis', models.CharField(max_length=50)),
                ('status_baca', models.BooleanField(default=False)),
                ('tanggal_dibuat', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perusahaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_instansi', models.CharField(max_length=255)),
                ('alamat', models.TextField()),
                ('kontak_supervisor', models.CharField(max_length=50)),
                ('deskripsi_pekerjaan', models.TextField()),
                ('kuota_maksimal', models.IntegerField()),
                ('status_mitra', models.CharField(max_length=50)),
                ('tanggal_bergabung', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nisn', models.CharField(max_length=50, unique=True)),
                ('jurusan', models.CharField(max_length=100)),
                ('kelas', models.CharField(max_length=50)),
                ('no_hp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorPerusahaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=20)),
                ('id_perusahaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to='magang.perusahaan')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Siswa', 'Siswa'), ('Guru', 'Guru'), ('Supervisor', 'Supervisor')], max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('kontak', models.CharField(max_length=50)),
                ('status_aktif', models.CharField(max_length=50)),
                ('tanggal_dibuat', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Magang',
        ),
        migrations.AddField(
            model_name='lamaran',
            name='id_lowongan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lamaran_lowongan', to='magang.lowongan'),
        ),
        migrations.AddField(
            model_name='laporan',
            name='id_magang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_magang', to='magang.magangpenempatan'),
        ),
        migrations.AddField(
            model_name='jurnalharian',
            name='id_magang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurnal_magang', to='magang.magangpenempatan'),
        ),
        migrations.AddField(
            model_name='magangpenempatan',
            name='id_perusahaan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penempatan_perusahaan', to='magang.perusahaan'),
        ),
        migrations.AddField(
            model_name='lowongan',
            name='id_perusahaan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lowongan_perusahaan', to='magang.perusahaan'),
        ),
        migrations.AddField(
            model_name='magangpenempatan',
            name='id_siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penempatan_siswa', to='magang.siswa'),
        ),
        migrations.AddField(
            model_name='lamaran',
            name='id_siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lamaran_siswa', to='magang.siswa'),
        ),
        migrations.AddField(
            model_name='supervisorperusahaan',
            name='id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_profile', to='magang.user'),
        ),
        migrations.AddField(
            model_name='siswa',
            name='id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='siswa_profile', to='magang.user'),
        ),
        migrations.AddField(
            model_name='perusahaan',
            name='id_user_supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perusahaan_supervisor', to='magang.user'),
        ),
        migrations.AddField(
            model_name='notifikasi',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi_user', to='magang.user'),
        ),
        migrations.AddField(
            model_name='gurupembimbing',
            name='id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guru_profile', to='magang.user'),
        ),
        migrations.AddField(
            model_name='admin',
            name='id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='magang.user'),
        ),
    ]
